@startuml
'https://plantuml.com/class-diagram

class todo
class mainController
class openController
class saveController
class editController

class todo {
root = "mainTodo.fxml"
Scene scene
Stage primaryStage
changeScene(): takes in specified fxml file name to change window
}

todo *-- mainController

class mainController {
newFile(): creates new .txt file
openFile(): opens existing .txt file
exportFile(): exports current file to .txt file
--
newList(): creates new todo list within file
openList(): opens currently selected todo list within file
deleteList(): deletes selected todo list
}

mainController o- openController: openFile() >
mainController o-- saveController: exportFile() >

mainController --|> editController: newList() - openList() >
editController --|> mainController: saveList() >

class editController {
newTodo(): creates new todo within current list
deleteTodo(): deletes selected todo
nameList(): changes name of current todo list
saveList(): returns current todo list back to mainController
exportList(): exports list to .txt file
filterStatus(): program will cycle through various filters of completed / incomplete / all
--
editTodoName(): changes name of current todo item
markCompleted(): mark todo item as completed or incomplete
editDate(): changes due date of todo item
editDescription(): changes description of todo item
}

editController o-- saveController: exportList() >

class openController {
Prompts for file path of file to open.
Passes back file path.
}

class saveController {
Prompts for file path to save .txt file at.
Passes back file path.
}



@enduml